server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smalnote?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: smalnote
    password: smalnote
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT CURRENT_TIMESTAMP()

logging:
  config: 'classpath:log4j2.xml'
  level:
    root: info
    web: info

mybatis:
  mapper-locations: 'classpath:mybatis/mapper/*.xml'
  type-aliases-package: com.github.smalnote.heron.model

tcp:
  enabled: true
  configs:
    - env: DEV
      mac: SZ01
      ip: 192.168.0.1
      port: 80
    - env: ST
      mac: SZ02
      ip: 192.168.0.2
      port: 8080

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/smalnote?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: smalnote
    password: smalnote
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT CURRENT_TIMESTAMP()
logging:
  level:
    root: info
    web: info
    com.github.smalnote.heron: debug
---

heron:
  appId: ${random.uuid}


tcp.config:
  - env: DEV
    mac: SZ01
    ip: 192.168.0.1
    port: 3306
  - env: ST
    mac: SH01
    ip: 128.0.0.1
    port: 3326
  - env: UAT
    mac: SH02
    ip: 10.0.0.1
    port: 3302